# Generated by Django 4.2 on 2023-04-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_errors',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='test',
            name='questions_count',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='test',
            name='time_to_pass',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
