# Generated by Django 4.2 on 2023-04-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_remove_usertestresult_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertestresult',
            name='score',
        ),
        migrations.AddField(
            model_name='usertestresult',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
